# docker-compose.monitoring.yml
version: '3.7'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      # Mount your config file into the container
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090" # Access Prometheus on http://localhost:9090
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000" # Access Grafana on http://localhost:3000
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge